name: Build Executable

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write  # Required for creating releases

jobs:
  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Build for Windows
      env:
        GOOS: windows
        GOARCH: amd64
        CGO_ENABLED: 0
      run: |
        go build -v -ldflags="-s -w" -o vaobs.exe .
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: vaobs-windows-executable
        path: vaobs.exe
        retention-days: 30
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        FILE_SIZE=$(du -h vaobs.exe | cut -f1)
        cat > release_notes.md << EOF
        Release $TAG_NAME
        
        File Information:
        - vaobs.exe: Windows executable (${FILE_SIZE})
        
        Installation:
        Download the vaobs.exe file and run it directly on Windows in cmd. Use `--help` to see available commands.
        EOF
        gh release create "$TAG_NAME" vaobs.exe \
          --title "VaOBS $TAG_NAME" \
          --notes-file release_notes.md \
          --verify-tag
